function backtest()
    data = IBMatlab('action','history', 'symbol','TSLA', ...
        'barSize','5 secs', 'useRTH',0, ...
        'DurationValue',1, 'DurationUnits','D');
    bar = struct('symbol', 'TSLA', 'data', data);
    p = struct( ...
        'slow', 26, ...
        'fast', 12, ...
        'macd', 9, ...
        'upper', 70, ...
        'lower', 30);
    dollar = 10000;
    exe(bar, dollar, p);
end

function [bar] = bar_window(start, m, symbol, data)
    data = struct( ...
        'open', data.open(start:start+m), ...
        'low', data.close(start:start+m), ...
        'high', data.high(start:start+m), ...
        'close', data.close(start:start+m));
    bar = struct('symbol', symbol, 'data', data);
end